version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: satudata-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: satudata
      POSTGRES_PASSWORD: satudata
      POSTGRES_DB: satudata
    volumes:
      - satudata-pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U satudata"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: satudata-redis
    ports:
      - "6380:6379"
    volumes:
      - satudata-redis:/data

  minio:
    image: minio/minio:latest
    container_name: satudata-minio
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - satudata-minio:/data
    command: server /data --console-address ":9001"

  nats:
    image: nats:latest
    container_name: satudata-nats
    ports:
      - "4223:4222"
      - "8223:8222"
    command: -js

  mongo:
    image: mongo:7
    container_name: satudata-mongo
    ports:
      - "27018:27017"
    volumes:
      - satudata-mongodb:/data/db

volumes:
  satudata-pgdata:
  satudata-redis:
  satudata-minio:
  satudata-mongodb:
